server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: proman-api

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        temp:
          use_jbdc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL10Dilect